const EDITOR_LANGUAGE_BY_EXTENSION: Record<string, string> = {
  '.bat': 'batchfile',
  '.c': 'c_cpp',
  '.cc': 'c_cpp',
  '.cjs': 'javascript',
  '.cmd': 'batchfile',
  '.coffee': 'coffee',
  '.conf': 'ini',
  '.cpp': 'c_cpp',
  '.cs': 'csharp',
  '.cxx': 'c_cpp',
  '.cts': 'typescript',
  '.astro': 'html',
  '.dart': 'dart',
  '.env': 'ini',
  '.erl': 'erlang',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.fish': 'sh',
  '.fs': 'fsharp',
  '.fsi': 'fsharp',
  '.fsx': 'fsharp',
  '.go': 'golang',
  '.groovy': 'groovy',
  '.h': 'c_cpp',
  '.hh': 'c_cpp',
  '.hpp': 'c_cpp',
  '.hxx': 'c_cpp',
  '.htm': 'html',
  '.html': 'html',
  '.ini': 'ini',
  '.java': 'java',
  '.jl': 'julia',
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.less': 'less',
  '.lua': 'lua',
  '.m': 'objectivec',
  '.markdown': 'markdown',
  '.md': 'markdown',
  '.mdx': 'markdown',
  '.mm': 'objectivec',
  '.mjs': 'javascript',
  '.mts': 'typescript',
  '.nim': 'nim',
  '.php': 'php',
  '.pl': 'perl',
  '.pm': 'perl',
  '.ps1': 'powershell',
  '.py': 'python',
  '.r': 'r',
  '.rb': 'ruby',
  '.rs': 'rust',
  '.sass': 'sass',
  '.scala': 'scala',
  '.scss': 'scss',
  '.sh': 'sh',
  '.sql': 'sql',
  '.swift': 'swift',
  '.toml': 'toml',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.vbs': 'vbscript',
  '.svelte': 'html',
  '.vue': 'vue',
  '.xml': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.zig': 'zig',
}

const EDITOR_LANGUAGE_BY_BASENAME: Record<string, string> = {
  'brewfile': 'ruby',
  'build.gradle': 'groovy',
  'build.gradle.kts': 'kotlin',
  'cmakelists.txt': 'cmake',
  'containerfile': 'dockerfile',
  'dockerfile': 'dockerfile',
  'gnumakefile': 'makefile',
  'gemfile': 'ruby',
  'justfile': 'makefile',
  'makefile': 'makefile',
  'podfile': 'ruby',
  'procfile': 'ini',
  'rakefile': 'ruby',
  'vagrantfile': 'ruby',
  'wasm.toml': 'toml',
  'workspace': 'plaintext',
  'xmake.lua': 'lua',
}

const HIGHLIGHT_LANGUAGE_BY_EXTENSION: Record<string, string> = {
  '.astro': 'xml',
  '.bat': 'dos',
  '.c': 'c',
  '.cc': 'cpp',
  '.cmake': 'cmake',
  '.cmd': 'dos',
  '.coffee': 'coffeescript',
  '.cjs': 'javascript',
  '.conf': 'ini',
  '.cpp': 'cpp',
  '.cs': 'csharp',
  '.cxx': 'cpp',
  '.cts': 'typescript',
  '.dart': 'dart',
  '.env': 'ini',
  '.erl': 'erlang',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.dockerfile': 'dockerfile',
  '.fish': 'bash',
  '.fs': 'fsharp',
  '.fsi': 'fsharp',
  '.fsx': 'fsharp',
  '.go': 'go',
  '.gql': 'graphql',
  '.gradle': 'gradle',
  '.graphql': 'graphql',
  '.groovy': 'groovy',
  '.h': 'c',
  '.hh': 'cpp',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.htm': 'html',
  '.html': 'html',
  '.ini': 'ini',
  '.java': 'java',
  '.jl': 'julia',
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.less': 'less',
  '.lua': 'lua',
  '.m': 'objectivec',
  '.markdown': 'markdown',
  '.md': 'markdown',
  '.mdx': 'markdown',
  '.mm': 'objectivec',
  '.mjs': 'javascript',
  '.nim': 'nim',
  '.php': 'php',
  '.phtml': 'php-template',
  '.pl': 'perl',
  '.pm': 'perl',
  '.proto': 'protobuf',
  '.properties': 'properties',
  '.ps1': 'powershell',
  '.py': 'python',
  '.r': 'r',
  '.rb': 'ruby',
  '.rs': 'rust',
  '.sass': 'sass',
  '.scala': 'scala',
  '.scss': 'scss',
  '.sh': 'bash',
  '.sql': 'sql',
  '.svelte': 'xml',
  '.swift': 'swift',
  '.tex': 'latex',
  '.toml': 'ini',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.vb': 'vbnet',
  '.vbs': 'vbscript',
  '.vue': 'xml',
  '.xml': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.zig': 'zig',
}

const HIGHLIGHT_LANGUAGE_BY_BASENAME: Record<string, string> = {
  'brewfile': 'ruby',
  'build.gradle': 'gradle',
  'build.gradle.kts': 'kotlin',
  'cmakelists.txt': 'cmake',
  'containerfile': 'dockerfile',
  'dockerfile': 'dockerfile',
  'gnumakefile': 'makefile',
  'gemfile': 'ruby',
  'justfile': 'makefile',
  'makefile': 'makefile',
  'podfile': 'ruby',
  'procfile': 'ini',
  'rakefile': 'ruby',
  'vagrantfile': 'ruby',
  'xmake.lua': 'lua',
}

const HIGHLIGHT_LANGUAGE_CANONICAL_BY_ALIAS: Record<string, string> = {
  bash: 'bash',
  batch: 'dos',
  batchfile: 'dos',
  bat: 'dos',
  c: 'c',
  'c#': 'csharp',
  'c++': 'cpp',
  cts: 'typescript',
  cjs: 'javascript',
  cmake: 'cmake',
  coffee: 'coffeescript',
  coffeescript: 'coffeescript',
  cmd: 'dos',
  cpp: 'cpp',
  csharp: 'csharp',
  css: 'css',
  dart: 'dart',
  docker: 'dockerfile',
  dockerfile: 'dockerfile',
  dos: 'dos',
  edn: 'clojure',
  elixir: 'elixir',
  erlang: 'erlang',
  'f#': 'fsharp',
  fish: 'bash',
  fs: 'fsharp',
  fsharp: 'fsharp',
  gql: 'graphql',
  go: 'go',
  golang: 'go',
  gradle: 'gradle',
  graphql: 'graphql',
  groovy: 'groovy',
  h: 'c',
  haskell: 'haskell',
  htm: 'xml',
  html: 'xml',
  ini: 'ini',
  java: 'java',
  javascript: 'javascript',
  javascriptreact: 'javascript',
  js: 'javascript',
  json: 'json',
  json5: 'json',
  jsonc: 'json',
  jsx: 'javascript',
  jupyter: 'python',
  julia: 'julia',
  kotlin: 'kotlin',
  kt: 'kotlin',
  kts: 'kotlin',
  less: 'less',
  lua: 'lua',
  markdown: 'markdown',
  md: 'markdown',
  mdx: 'markdown',
  mjs: 'javascript',
  mts: 'typescript',
  mm: 'objectivec',
  mysql: 'sql',
  nginx: 'nginx',
  nim: 'nim',
  objectivec: 'objectivec',
  'objective-c': 'objectivec',
  objc: 'objectivec',
  perl: 'perl',
  php: 'php',
  phtml: 'php-template',
  pl: 'perl',
  powershell: 'powershell',
  proto: 'protobuf',
  protobuf: 'protobuf',
  properties: 'properties',
  ps1: 'powershell',
  py: 'python',
  python: 'python',
  r: 'r',
  rb: 'ruby',
  restructuredtext: 'restructuredtext',
  rs: 'rust',
  ruby: 'ruby',
  rust: 'rust',
  sass: 'sass',
  scala: 'scala',
  scss: 'scss',
  shell: 'bash',
  shellscript: 'bash',
  sh: 'bash',
  sql: 'sql',
  swift: 'swift',
  text: 'plaintext',
  tex: 'latex',
  toml: 'ini',
  ts: 'typescript',
  tsx: 'typescript',
  typescript: 'typescript',
  typescriptreact: 'typescript',
  vb: 'vbnet',
  vbnet: 'vbnet',
  vbscript: 'vbscript',
  vbs: 'vbscript',
  astro: 'xml',
  svelte: 'xml',
  vue: 'xml',
  xml: 'xml',
  yml: 'yaml',
  yaml: 'yaml',
  zig: 'zig',
  zsh: 'bash',
}

export const HIGHLIGHT_LANGUAGE_ALIASES: Record<string, string[]> = Object.entries(
  HIGHLIGHT_LANGUAGE_CANONICAL_BY_ALIAS,
).reduce((aliases, [alias, language]) => {
  if (alias === language) return aliases
  aliases[language] = [...(aliases[language] ?? []), alias]
  return aliases
}, {} as Record<string, string[]>)

function normalizeLanguageToken(value: string): string {
  const token = value.trim().split(/\s+/u)[0]?.toLowerCase() ?? ''
  return token
}

function basenameFromPath(pathValue: string): string {
  const normalizedPath = pathValue.trim().replace(/\\/gu, '/').replace(/\/+$/u, '')
  if (!normalizedPath) return ''
  const slashIndex = normalizedPath.lastIndexOf('/')
  return slashIndex >= 0 ? normalizedPath.slice(slashIndex + 1) : normalizedPath
}

function extnameFromPath(pathValue: string): string {
  const base = basenameFromPath(pathValue)
  if (!base) return ''
  const lastDotIndex = base.lastIndexOf('.')
  if (lastDotIndex <= 0) return ''
  return base.slice(lastDotIndex).toLowerCase()
}

function resolveLanguageForPath(
  pathValue: string,
  byBasename: Record<string, string>,
  byExtension: Record<string, string>,
): string {
  const normalizedPath = pathValue.trim()
  if (!normalizedPath) return 'plaintext'

  const normalizedBasename = basenameFromPath(normalizedPath).toLowerCase()
  const basenameLanguage = byBasename[normalizedBasename]
  if (basenameLanguage) return basenameLanguage

  const extension = extnameFromPath(normalizedPath)
  return byExtension[extension] ?? 'plaintext'
}

export function getEditorModeForPath(pathValue: string): string {
  return resolveLanguageForPath(pathValue, EDITOR_LANGUAGE_BY_BASENAME, EDITOR_LANGUAGE_BY_EXTENSION)
}

export function getHighlightLanguageForPath(pathValue: string): string {
  return resolveLanguageForPath(pathValue, HIGHLIGHT_LANGUAGE_BY_BASENAME, HIGHLIGHT_LANGUAGE_BY_EXTENSION)
}

export function normalizeHighlightLanguage(language: string): string {
  const token = normalizeLanguageToken(language)
  if (!token) return ''
  return HIGHLIGHT_LANGUAGE_CANONICAL_BY_ALIAS[token] ?? token
}
